package net.grimveil.entity.client;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class ShadeAnimations {
    public static final Animation ANIM_SHADE_IDLE = Animation.Builder.create(3f).looping()
            .addBoneAnimation("Head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.18159806295399517f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4527845036319613f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9661016949152543f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.24213075060532688f, AnimationHelper.createRotationalVector(19.87f, -2.25f, 7.14f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7263922518159807f, AnimationHelper.createRotationalVector(22.31f, -5.04f, 7.23f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7869249394673123f, AnimationHelper.createRotationalVector(21.47f, -1.12f, 17f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8474576271186441f, AnimationHelper.createRotationalVector(22.49f, -6.02f, 11.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9079903147699758f, AnimationHelper.createRotationalVector(22.31f, -5.04f, 7.23f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4527845036319613f, AnimationHelper.createRotationalVector(24.75f, -7.83f, 7.31f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.179176755447942f, AnimationHelper.createRotationalVector(22.41f, -5.15f, 7.23f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2397094430992737f, AnimationHelper.createRotationalVector(25.27f, -3.81f, -0.66f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3002421307506054f, AnimationHelper.createRotationalVector(18.82f, -6.93f, -2.83f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.360774818401937f, AnimationHelper.createRotationalVector(21.24f, -3.81f, 7.19f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9055690072639226f, AnimationHelper.createRotationalVector(19.87f, -2.25f, 7.14f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Torso",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.089588377723971f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.542372881355932f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Torso",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.089588377723971f, AnimationHelper.createRotationalVector(8.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.542372881355932f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Left_Leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0.4f, -0.25f, 0.6f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Left_Leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(7.13f, -9.74f, -3.33f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Right_Leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(-0.25f, -0.5f, -0.8f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Right_Leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(2.63f, 2.49f, 2.72f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Left_Arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.12106537530266344f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4527845036319613f, AnimationHelper.createTranslationalVector(0f, -1.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5738498789346247f, AnimationHelper.createTranslationalVector(0f, -1.33f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6343825665859564f, AnimationHelper.createTranslationalVector(0f, -1.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.7845036319612593f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Left_Arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.18159806295399517f, AnimationHelper.createRotationalVector(-4.96f, 1.84f, -7.69f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4527845036319613f, AnimationHelper.createRotationalVector(-4.78f, 2.26f, -2.7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.513317191283293f, AnimationHelper.createRotationalVector(-5.43f, 11.99f, -6.3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5738498789346247f, AnimationHelper.createRotationalVector(-5.73f, 11.82f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6343825665859564f, AnimationHelper.createRotationalVector(-4.82f, 2.18f, -3.7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9055690072639226f, AnimationHelper.createRotationalVector(-4.96f, 1.84f, -7.69f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Right_Arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -1.25f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4527845036319613f, AnimationHelper.createTranslationalVector(0f, -1.5f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.845036319612591f, AnimationHelper.createTranslationalVector(0f, -1.25f, -0.75f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Right_Arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-7.57f, -9.26f, 6.27f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4527845036319613f, AnimationHelper.createRotationalVector(-7.16f, -9.58f, 3.76f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9055690072639226f, AnimationHelper.createRotationalVector(-7.57f, -9.26f, 6.27f),
                                    Transformation.Interpolations.LINEAR))).build();

    public static final Animation ANIM_SHADE_WALK = Animation.Builder.create(1.1134333f).looping()
            .addBoneAnimation("Head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.37037037037037035f, AnimationHelper.createTranslationalVector(0f, -0.2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6296296296296297f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9629629629629629f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-2.5f, 0.11f, 2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2222222222222222f, AnimationHelper.createRotationalVector(-7.28f, 5.71f, 6.81f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4444444444444444f, AnimationHelper.createRotationalVector(0.05f, -0.87f, -4.94f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5925925925925926f, AnimationHelper.createRotationalVector(-7.56f, -0.87f, 2.56f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7037037037037037f, AnimationHelper.createRotationalVector(-2.6f, -3.02f, 5.37f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8888888888888888f, AnimationHelper.createRotationalVector(-7.8f, -12.89f, 8.36f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0740740740740742f, AnimationHelper.createRotationalVector(-2.5f, 0.11f, 2.5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Torso",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.037037037037037035f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0.35f, -0.3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5185185185185185f, AnimationHelper.createTranslationalVector(0f, -0.45f, -0.3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1111111111111112f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Torso",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2222222222222222f, AnimationHelper.createRotationalVector(5.03f, -7.91f, 4.33f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5555555555555556f, AnimationHelper.createRotationalVector(17.64f, 8.65f, -2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7037037037037037f, AnimationHelper.createRotationalVector(1.71f, -1.2f, -4.21f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8888888888888888f, AnimationHelper.createRotationalVector(16.92f, 13.67f, -1.74f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0740740740740742f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Left_Leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0.4f, -0.25f, 0.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.14814814814814814f, AnimationHelper.createTranslationalVector(0.4f, -0.85f, 1.1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5555555555555556f, AnimationHelper.createTranslationalVector(0.4f, -0.45f, 1.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407407f, AnimationHelper.createTranslationalVector(0.4f, 0.95f, -1.7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8518518518518519f, AnimationHelper.createTranslationalVector(0.4f, -0.85f, -2.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0.4f, -0.25f, 0.6f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Left_Leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(7.13f, -9.74f, -3.33f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25925925925925924f, AnimationHelper.createRotationalVector(21.97f, -0.92f, -5.15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.48148148148148145f, AnimationHelper.createRotationalVector(22f, -3.23f, -6.09f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createRotationalVector(7f, -3.23f, -6.09f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9259259259259259f, AnimationHelper.createRotationalVector(8.53f, 3.58f, -0.92f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0740740740740742f, AnimationHelper.createRotationalVector(7.13f, -9.74f, -3.33f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Right_Leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.07407407407407407f, AnimationHelper.createTranslationalVector(-0.25f, -0.5f, -0.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(-0.25f, 1.1f, -1.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5555555555555556f, AnimationHelper.createTranslationalVector(-0.25f, -0.5f, -2.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8148148148148148f, AnimationHelper.createTranslationalVector(-0.75f, -0.9f, 0.81f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0740740740740742f, AnimationHelper.createTranslationalVector(-0.25f, -0.5f, -0.8f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Right_Leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(2.63f, 2.49f, 2.72f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2222222222222222f, AnimationHelper.createRotationalVector(-7.39f, -7.5f, 3.14f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6296296296296297f, AnimationHelper.createRotationalVector(5.2f, 9.96f, 3.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8888888888888888f, AnimationHelper.createRotationalVector(24.82f, -1.18f, 4.18f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1111111111111112f, AnimationHelper.createRotationalVector(2.63f, 2.49f, 2.72f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Left_Arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.18518518518518517f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5185185185185185f, AnimationHelper.createTranslationalVector(0f, -1f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8148148148148148f, AnimationHelper.createTranslationalVector(0.3f, -2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1111111111111112f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Left_Arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.07407407407407407f, AnimationHelper.createRotationalVector(-4.96f, 1.84f, -7.69f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4074074074074074f, AnimationHelper.createRotationalVector(-30.3f, 11.74f, -10.56f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7037037037037037f, AnimationHelper.createRotationalVector(19.69f, -11.71f, -8.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0740740740740742f, AnimationHelper.createRotationalVector(-4.96f, 1.84f, -7.69f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Right_Arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.1111111111111111f, AnimationHelper.createTranslationalVector(0f, -1.25f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5555555555555556f, AnimationHelper.createTranslationalVector(0f, -1.55f, 1.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8148148148148148f, AnimationHelper.createTranslationalVector(0.3f, -0.85f, -1.05f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.037037037037037f, AnimationHelper.createTranslationalVector(0f, -1.25f, -0.75f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("Right_Arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.18518518518518517f, AnimationHelper.createRotationalVector(-7.57f, -9.26f, 6.27f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4444444444444444f, AnimationHelper.createRotationalVector(13.97f, 13.74f, 7.09f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407407f, AnimationHelper.createRotationalVector(-21.92f, -10.88f, 14.85f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1111111111111112f, AnimationHelper.createRotationalVector(-7.57f, -9.26f, 6.27f),
                                    Transformation.Interpolations.LINEAR))).build();

    public static final Animation ANIM_SHADE_ATTACK = Animation.Builder.create(0.8F)
            .addBoneAnimation("Head", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(-4.9976F, -0.109F, -2.4976F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2F, AnimationHelper.createRotationalVector(-9.6275F, -14.2457F, 6.5479F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4667F, AnimationHelper.createRotationalVector(-7.3485F, -4.1819F, -0.1459F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.7333F, AnimationHelper.createRotationalVector(-4.9976F, -0.109F, -2.4976F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Head", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.1F, AnimationHelper.createTranslationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2333F, AnimationHelper.createTranslationalVector(0.0F, 0.1F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4F, AnimationHelper.createTranslationalVector(0.0F, 0.2F, -0.5F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.5333F, AnimationHelper.createTranslationalVector(0.0F, 0.3F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6333F, AnimationHelper.createTranslationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Torso", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(7.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2F, AnimationHelper.createRotationalVector(6.6504F, 16.6062F, 7.5221F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.5F, AnimationHelper.createRotationalVector(16.4042F, -5.7517F, 4.9692F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6667F, AnimationHelper.createRotationalVector(7.5F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Torso", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.1F, AnimationHelper.createTranslationalVector(0.0F, -0.25F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2333F, AnimationHelper.createTranslationalVector(0.0F, -0.25F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4F, AnimationHelper.createTranslationalVector(0.0F, -0.25F, -1.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.7667F, AnimationHelper.createTranslationalVector(0.0F, -0.25F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Left_Leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(7.1279F, -9.7376F, -3.3303F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667F, AnimationHelper.createRotationalVector(12.1279F, -9.7376F, -3.3303F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4667F, AnimationHelper.createRotationalVector(4.3356F, -3.708F, -5.5619F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.7333F, AnimationHelper.createRotationalVector(7.1279F, -9.7376F, -3.3303F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Left_Leg", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0333F, AnimationHelper.createTranslationalVector(0.4F, -0.25F, 0.6F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2333F, AnimationHelper.createTranslationalVector(0.9F, -0.25F, -0.5F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.3667F, AnimationHelper.createTranslationalVector(0.4F, -0.65F, -2.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6333F, AnimationHelper.createTranslationalVector(0.4F, -0.25F, 0.6F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Right_Leg", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(2.6283F, 2.4928F, 2.7204F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667F, AnimationHelper.createRotationalVector(10.294F, 19.9736F, 3.5611F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4333F, AnimationHelper.createRotationalVector(10.2924F, -3.4854F, 6.9689F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.7333F, AnimationHelper.createRotationalVector(2.6283F, 2.4928F, 2.7204F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Right_Leg", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0667F, AnimationHelper.createTranslationalVector(-0.25F, -0.5F, -0.8F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2F, AnimationHelper.createTranslationalVector(-1.25F, -0.5F, -0.8F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.3667F, AnimationHelper.createTranslationalVector(-0.65F, -0.5F, -0.4F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6333F, AnimationHelper.createTranslationalVector(-0.25F, -0.5F, -0.8F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Left_Arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(-4.9597F, 1.8388F, -7.6879F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1333F, AnimationHelper.createRotationalVector(-17.7003F, 2.9719F, -31.2941F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.3F, AnimationHelper.createRotationalVector(-64.9818F, -7.5375F, -56.1839F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4667F, AnimationHelper.createRotationalVector(-75.5505F, -1.5626F, -49.9229F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6F, AnimationHelper.createRotationalVector(-34.1802F, 33.1286F, -23.3274F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.7667F, AnimationHelper.createRotationalVector(-4.9597F, 1.8388F, -7.6879F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Left_Arm", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0667F, AnimationHelper.createTranslationalVector(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2F, AnimationHelper.createTranslationalVector(0.0F, 0.0F, 3.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2667F, AnimationHelper.createTranslationalVector(0.0F, -1.0F, 3.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4F, AnimationHelper.createTranslationalVector(0.0F, -1.0F, -2.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.5333F, AnimationHelper.createTranslationalVector(0.5F, -1.3F, -1.2F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.7F, AnimationHelper.createTranslationalVector(0.0F, -1.0F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Right_Arm", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(-7.5706F, -9.2626F, 6.2684F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667F, AnimationHelper.createRotationalVector(-36.2378F, -4.7519F, 49.6479F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2333F, AnimationHelper.createRotationalVector(-52.1279F, -5.3762F, 69.1481F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4667F, AnimationHelper.createRotationalVector(-86.8853F, 2.4931F, 51.99F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6333F, AnimationHelper.createRotationalVector(-61.3615F, -40.5869F, 38.6284F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.8F, AnimationHelper.createRotationalVector(-7.5706F, -9.2626F, 6.2684F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("Right_Arm", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0333F, AnimationHelper.createTranslationalVector(0.0F, -1.25F, -0.75F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1333F, AnimationHelper.createTranslationalVector(0.0F, -0.25F, 1.25F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2667F, AnimationHelper.createTranslationalVector(0.0F, 0.75F, 2.25F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.3667F, AnimationHelper.createTranslationalVector(0.0F, -0.25F, -2.75F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.5F, AnimationHelper.createTranslationalVector(0.0F, -2.25F, -2.75F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.7333F, AnimationHelper.createTranslationalVector(0.0F, -1.25F, -0.75F), Transformation.Interpolations.LINEAR)
            ))
            .build();
}
